services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.98.0
    command: ["--config=/etc/otelcol/config.yaml"]
    volumes:
      - ./infra/otel-collector/otel-collector.loki.yaml:/etc/otelcol/config.yaml:ro
    ports:
      - "4317:4317"
      - "4318:4318"
    depends_on:
      - loki
    restart: unless-stopped

  loki:
    image: grafana/loki:2.9.4
    ports:
      - "3100:3100"
    command: ["-config.file=/etc/loki/local-config.yaml"]
    restart: unless-stopped

  grafana:
    image: grafana/grafana:10.3.3
    ports:
      - "3001:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - loki
    restart: unless-stopped

volumes:
  grafana-data:
