"""add_actor_attribution_columns

Revision ID: bb84bcfc709a
Revises: 20240925_add_audit_hash_chain
Create Date: 2026-02-03 22:52:31.776334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb84bcfc709a'
down_revision: Union[str, None] = '20240925_add_audit_hash_chain'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('action_history', sa.Column('requested_by_user_id', sa.String(length=255), nullable=True))
    op.add_column('action_history', sa.Column('requested_by_role', sa.String(length=50), nullable=True))
    op.add_column('action_history', sa.Column('requested_by_key_id', sa.String(length=64), nullable=True))
    op.add_column('action_history', sa.Column('approved_by_user_id', sa.String(length=255), nullable=True))
    op.add_column('action_history', sa.Column('approved_by_role', sa.String(length=50), nullable=True))
    op.add_column('action_history', sa.Column('approved_by_key_id', sa.String(length=64), nullable=True))
    op.add_column('action_history', sa.Column('executed_by_user_id', sa.String(length=255), nullable=True))
    op.add_column('action_history', sa.Column('executed_by_role', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_action_history_approved_by_user_id'), 'action_history', ['approved_by_user_id'], unique=False)
    op.create_index(op.f('ix_action_history_requested_by_user_id'), 'action_history', ['requested_by_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_action_history_requested_by_user_id'), table_name='action_history')
    op.drop_index(op.f('ix_action_history_approved_by_user_id'), table_name='action_history')
    op.drop_column('action_history', 'executed_by_role')
    op.drop_column('action_history', 'executed_by_user_id')
    op.drop_column('action_history', 'approved_by_key_id')
    op.drop_column('action_history', 'approved_by_role')
    op.drop_column('action_history', 'approved_by_user_id')
    op.drop_column('action_history', 'requested_by_key_id')
    op.drop_column('action_history', 'requested_by_role')
    op.drop_column('action_history', 'requested_by_user_id')
    # ### end Alembic commands ###
